FROM alpine:latest
RUN apk update
RUN apk add --no-cache libpcap libpcap-dev msgpack-c msgpack-c-dev libstdc++
RUN mkdir /opt/
WORKDIR /opt/

RUN apk add --no-cache --virtual .build-deps git cmake clang automake alpine-sdk && \
		git clone --recursive https://github.com/m-mizutani/dns-gazer.git && \
		cd dns-gazer && \
		cmake . && \
		make install && \
		apk del .build-deps && \
		rm -rf /opt/dns-gazer
CMD /usr/local/bin/dns-gazer -i $DEVICE -f $FLUENTD_ADDRESS
